### ISSUE TITLE
专有名词使用正确的大小写

### ISSUE THREAD

**Issue by Geeyun-JY3** [Sealt/fooView-doc#16]
扣些小细节，如 README 和用户评价中的 `GooglePlay`，README  中的 `Github`，希望尽量以官方网站写法为准，分别改为 `Google Play` 和 `GitHub`。

还有正文中大量存在的中英文之间无增加空格，不过这个慢慢来吧，扫了一下感觉没加的地方太多了，一时半会也改不完。

**Comment by Sealt** [comment]
采纳，今后逐步修正。
