### ISSUE TITLE
文字选取的问题

### ISSUE THREAD

**Issue by shanehh** [Sealt/fooView-doc#4]
![IMG_20200318_185826](https://user-images.githubusercontent.com/49306726/76954031-a0883980-694a-11ea-962e-d4583e6e5624.jpg)
![IMG_20200318_185845](https://user-images.githubusercontent.com/49306726/76954038-a41bc080-694a-11ea-930d-ad8628025af9.jpg)

用 fooview 选取一个段落，会从 colored word 截断

文档写得很棒，感谢

**Comment by Sealt** [comment]
你好，已经帮您反馈至 fooView 官方。鉴于这里是文档区域，如果有软件上的问题直接邮件给 feedback@fooview.com即可，以便获取最佳反馈体验。相关文档问题可发出issus或联系我。
